name: Telegram Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get Telegram updates
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          curl -s "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getUpdates"
